apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2019-04-09T05:02:05Z"
  labels:
    app: prometheus
    chart: prometheus-8.9.0
    component: kube-state-metrics
    heritage: Tiller
    release: prometheus
  name: prometheus-kube-state-metrics
  namespace: kube-system
  resourceVersion: "1468968"
  selfLink: /api/v1/namespaces/kube-system/services/prometheus-kube-state-metrics
  uid: 9ee284e8-5a84-11e9-8eb0-001a4a160174
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: prometheus
    component: kube-state-metrics
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
